-- DML
-- 
--
--CREATE SEQUENCE MEMBER;
--CREATE TABLE TBL_MEMBER(
--	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
--	MEMBER_NAME VARCHAR2(255) NOT NULL,
--	MEMBER_AGE NUMBER,
--	MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
--	MEMBER_PHONE VARCHAR2(255),
--	MEMBER_GENDER CHAR(6),
--	MEMBER_CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--	MEMBER_CREATE_DATE DATE DEFAULT SYSDATE
--	
--);
--
--SELECT*FROM TBL_MEMBER;
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME,MEMBER_AGE,MEMBER_ADDRESS,MEMBER_PHONE,MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '홍길동', 46, '한양', '010-0000-0000', '남자');
--
--INSERT INTO TBL_MEMBER
--VALUES(SEQ_MEMBER.NEXTVAL, '장보고', 53, '경주', '010-1345-1234', '남자', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '이순신', 50, '성남시', '남자');
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '김철수', 35, '서울시 종로구', '남자');
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '김민수', 28, '경기도 하남시', '남자');
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '최규하', 24, '경기도 오산시', '남자');
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '김철민', 25, '경기도 성남시', '남자');
--
--
-- 데이터 추가
-- 김영희, 25살, 서울시 영등포구 
--
--INSERT INTO TBL_MEMBER
--VALUES (SEQ_MEMBER.NEXTVAL, '김영희', 25, '서울시 영등포구','010-2222-2222', '여자', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--
--UPDATE TBL_MEMBER SET MEMBER_GENDER = '여성'
--WHERE ID = 4;
--
--DROP TABLE TBL_MEMBER;
--DROP SEQUENCE MEMBER;
--DELETE FROM TABLE_MEMBER;
--
--DELETE FROM TBL_MEMBER
--WHERE ID = 5;
--
-- 이름이 홍길동인 사람의 전화번호를 010-4456-7788로 변경
-- 서울시 영등포구에 거주중인 사람의 데이터 삭제
--
--SELECT*FROM TBL_MEMBER;
--
--UPDATE TBL_MEMBER 
--SET MEMBER_PHONE = '010-4456-7788'
--WHERE MEMBER_NAME ='홍길동';
--
--DELETE TBL_MEMBER WHERE MEMBER_ADDRESS = '서울시 영등포구';
--
-- 나이가 20대인 사용자 
--
--SELECT*FROM TBL_MEMBER
--WHERE MEMBER_AGE > 19 AND MEMBER_AGE < 30;
--
--SELECT MEMBER_NAME, MEMBER_AGE
--FROM TBL_MEMBER
--WHERE MEMBER_GENDER = '남자';
--
--SELECT *
--FROM TBL_MEMBER
--WHERE MEMBER_ADDRESS LIKE '%시';
--
-- 종로에 살고있느 사용자 나이 조회
--SELECT MEMBER_AGE
--FROM TBL_MEMBER
--WHERE MEMBER_ADDRESS LIKE '%종로%';
--
--SELECT * FROM TBL_MEMBER WHERE MEMBER_PHONE IS NULL;
--
--SELECT *
--FROM TBL_MEMBER
--WHERE MEMBER_ADDRESS NOT LIKE '%경기도%';
--
--SELECT SYSDATE FROM DUAL;
--
-- ORACLE은 스크립트 언어
-- 같은 컬럼을 여러 번 조회할 수 있다.
-- ALIAS(별칭): 최종 테이블의 속성 이름을 변경할 수 있다.
-- 컬럼명 엎에 ""(더블쿼터) 사용하여 붙임.
--
--SELECT MEMBER_NAME "이름", MEMBER_AGE "회원 나이", MEMBER_AGE -1 "만 나이"
--FROM TBL_MEMBER;
--
-- 기존에 없던 테이블을 연산으로 만드는 것을 파생 변수
--
-- 연결 연산자 ||
--SELECT 'ABCD' || 'E' FROM DUAL;
--SELECT CONCAT('A', 'A') FROM DUAL;
--
-- NULL은 무시
--SELECT CONCAT('A', NULL) FROM DUAL;
--SELECT 'ABCD' || NULL FROM DUAL;
--
--
--SELECT MEMBER_NAME || '님' "이름" 
--FROM TBL_MEMBER;
--
-- 나이에 살을 붙여서 출력
--SELECT MEMBER_AGE || '살' "나이" FROM TBL_MEMBER;
--
--SELECT LENGTH(MEMBER_ADDRESS), MEMBER_ADDRESS
--FROM TBL_MEMBER;
--
-- 문자열 자르기 SUBSTR() 오라클은 인덱스가 1부터 시작함.
-- SUBSTR(찾을 글자, 시작 인덱스, 개수)
--SELECT SUBSTR('HELLO WORLD!', 6, 2)
--FROM TBL_MEMBER;
--
--SELECT MEMBER_AGE + 1 FROM TBL_MEMBER;
--SELECT MEMBER_AGE - 1 FROM TBL_MEMBER;
--SELECT MEMBER_AGE * 20 FROM TBL_MEMBER;
--
-- 올림
--SELECT CEIL(MEMBER_AGE / 5) FROM TBL_MEMBER;
-- 버림(몫)
--SELECT FLOOR(MEMBER_AGE / 5) FROM TBL_MEMBER;
-- 반올림
--SELECT ROUND(MEMBER_AGE / 5,3) FROM TBL_MEMBER;
-- 나머지 MOD
--SELECT MOD(MEMBER AGE, 5) FROM TBL_MEMBER;
--
-- 집계함수
--
--/*집계 함수
-- * 
-- * 평균 AVG()
-- * 최대값 MAX()
-- * 최소값 MIN()
-- * 총 합 SUM()
-- * 개수 COUNT()
-- * 
-- * */
--
--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--	PRODUCT_NAME VARCHAR2(255) NULL, 
--	PRODUCT_PRICE NUMBER DEFAULT 0,
--	PRODUCT_STOCK NUMBER DEFAULT 999,
--	PRODUCT_CREATE_AT DATE
--);
--
--INSERT INTO TBL_PRODUCT 
--VALUES(SEQ_PRODUCT.NEXTVAL, '텀블러', 15000, 10, TO_DATE('2026-01-02', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT 
--VALUES(SEQ_PRODUCT.NEXTVAL, '마스크', 25000, 10, TO_DATE('2026-01-02', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT 
--VALUES(SEQ_PRODUCT.NEXTVAL, '태양', 35000, 10, TO_DATE('2026-01-02', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT 
--VALUES(SEQ_PRODUCT.NEXTVAL, '아이폰', 45000, 10, TO_DATE('2026-01-02', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT 
--VALUES(SEQ_PRODUCT.NEXTVAL, '미', 55000, 10, TO_DATE('2026-01-02', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT 
--VALUES(SEQ_PRODUCT.NEXTVAL, '콜라', 65000, 10, TO_DATE('2026-01-02', 'YYYY-MM-DD HH24:mi'));
--
--SELECT*FROM TBL_PRODUCT;
--
-- 가장 비싼 상품은?
-- 그룹 함수, 집계 함수는 WHERE 절에서 사용이 불가능하다. 연산은 가능.
--SELECT MAX(PRODUCT_PRICE)
--FROM TBL_PRODUCT;
--
-- 상품의 총액 계산
--
--SELECT SUM(PRODUCT_PRICE * PRODUCT_STOCK) FROM TBL_PRODUCT;
--
-- 상품 등의 평균 가격
--SELECT AVG(PRODUCT_PRICE) FROM TBL_PRODUCT;
--
-- 태양,미,텀블러 가격의 평균
--SELECT AVG(PRODUCT_PRICE) || '원' "평균" 
--FROM TBL_PRODUCT 
--WHERE ID = 7 OR ID = 9 OR ID = 11;
--
--SELECT TO_CHAR(AVG(PRODUCT_PRICE), '999,999') || '원' "평균"
--FROM TBL_PRODUCT WHERE ID IN (7,9,11);
--
-- count 합계 함수는 NULL을 세지 않아 NULL이 아니라 0이 출력됨
--SELECT COUNT(NULL) FROM TBL_PRODUCT;
--
-- ORDER BY: 정렬
-- DESC 내림차순
-- ASC 오름차순
--
-- 낮은 가격 순
--SELECT*
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE ASC;
--
-- 높은 가격 순
--
--SELECT*
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC;
--
-- 최신 등록순
--SELECT *
--FROM TBL_PRODUCT 
--ORDER BY ID DESC;
--
-- 날짜의 연산
-- 일자 별로 계산
--SELECT PRODUCT_CREATE_AT, PRODUCT_CREATE_AT + 1 / 24 / 60
--FROM TBL_PRODUCT;
--
-- 가장 비싼 상품 조회
-- 처음부터 1행
--SELECT *
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--FETCH FIRST 3 ROWS ONLY;
--
-- 페이지네이션
-- OFFSET
--SELECT *
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--OFFSET (1 - 1) * 3 ROWS FETCH NEXT 3 ROWS ONLY;
--
--SELECT *
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--OFFSET (2 - 1) * 3 ROWS FETCH NEXT 3 ROWS ONLY;
--
--SELECT *
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--OFFSET (3 - 1) * 3 ROWS FETCH NEXT 3 ROWS ONLY;
--
--SELECT 500000 - 10000 FROM DUAL;
--
-- WHERE 절에서는 집계 함수, 그룹 함수 사용 불가!
--SELECT MAX(PRODUCT_PRICE) - 10000 FROM TBL_PRODUCT
--WHERE MAX(PRODUCT_PRICE) = 50000;

/*
 * GROUP BY: ~별
 * 
 * GROUP BY 컬럼명 HAVING 조건식
 * 
 * */

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_PRICE NUMBER DEFAULT 0,
   PRODUCT_STOCK NUMBER DEFAULT 999
);


SELECT * FROM TBL_PRODUCT;

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 2000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 3000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 4000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 6000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 5000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 2000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 60);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 2000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 3000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 30);

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 5000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 4000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 2000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 1000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 5000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 6000, 80);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 2000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 5000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 3000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 2000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 1000, 40);


INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 4000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 1000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 1000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 10);


-- HAVING
-- 상품 개수가 3개 이상인 상품 조회
SELECT
	PRODUCT_NAME, 
	PRODUCT_PRICE, 
	COUNT(PRODUCT_NAME),
	PRODUCT_PRICE * COUNT(PRODUCT_NAME)
FROM
	TBL_PRODUCT
GROUP BY
	PRODUCT_NAME,
	PRODUCT_PRICE
HAVING PRODUCT_PRICE >= 5000;

-- 상품의 가격대별 기대수익
SELECT
	'상품: ' || PRODUCT_NAME, 
	'가격: ' || TO_CHAR(PRODUCT_PRICE, '000,000,000') || '원' "상품가격",
	'기대수익: ' || TO_CHAR(PRODUCT_PRICE * SUM(PRODUCT_STOCK), '000,000') || '원' "기대수익"
FROM
	TBL_PRODUCT
GROUP BY
	PRODUCT_NAME, PRODUCT_PRICE;

-- 재고별 총 판매 액수
-- 서브쿼리에서 해결
--SELECT PRODUCT_STOCK, PRODUCT_PRICE * SUM(PRODUCT_STOCK), COUNT(PRODUCT_STOCK)
--FROM TBL_PRODUCT

-- 서브 쿼리
--GROUP BY PRODUCT_STOCK;

--서브 쿼리
-- 판매 가격 중에서 2000원이 초과되는 상품들 조회
SELECT TBP.*
FROM (
	SELECT *
	FROM TBL_PRODUCT
	WHERE PRODUCT_STOCK = 10
) TBP
WHERE TBP.PRODUCT_PRICE >= 2000;

-- 재고가 20, 30, 40인 상품들의 ID들을 조회

SELECT TBP.ID
FROM (

SELECT *
FROM TBL_PRODUCT
WHERE PRODUCT_STOCK IN (20, 30, 40)
) TBP;


-- 가장 비싼 상품 조회

SELECT *
FROM TBL_PRODUCT
WHERE PRODUCT_PRICE = (
	SELECT MAX(PRODUCT_PRICE)
	FROM TBL_PRODUCT
);
	
-- 판매 상품의 가격의 평균보다 비싼 상품들 조회

SELECT *
FROM TBL_PRODUCT
WHERE PRODUCT_PRICE >= (
	SELECT AVG(PRODUCT_PRICE)
	FROM TBL_PRODUCT
);

SELECT PRODUCT_PRICE, PRODUCT_STOCK * PRODUCT_PRICE
FROM TBL_PRODUCT;

-- 상품별
SELECT PRODUCT_NAME, PRODUCT_PRICE,
FROM TBL_PRODUCT
GROUP BY PRODUCT_NAME, PRODUCT_PRICE;

SELECT
	PRODUCT_NAME,
	PRODUCT_PRICE,
	SUM(PRODUCT_STOCK) * PRODUCT_PRICE,
	(
	SELECT
		PRODUCT_PRICE / 2
	FROM
		TBL_PRODUCT)
FROM
	TBL_PRODUCT
GROUP BY
	PRODUCT_NAME,
	PRODUCT_PRICE;

-- 서브쿼리
-- 유저, 게시판, 댓글
-- TBL_USER
-- 이메일(EMAIL), 비밀번호(PASSWORD), 주소(ADDRESS), 생일(BIRTH)

CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	USER_PASSWORD VARCHAR2(255),
	USER_ADDRESS VARCHAR2(255),
	USER_BIRTH DATE
);
-- 게시판(TBL_POST)
-- 제목(TITLE), 내용(CONTENT), 작성일(CREATE_AT)

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL,
	POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	USER_ID NUMBER,
	CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID)
);


-- 댓글(TBL_REPLY)
-- 내용(CONTENT)

CREATE SEUQENCE SEQ_REPLY;
CREATE TABLT TBL_REPLY(
	ID NUMBER CONSTRATE PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(255) NOT NULL,
	USER_ID NUMBER,
	POST_ID NUMBER,
	CONSTRAINT FK_REPLY_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID),
	CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
	REFERENCES TBL_POST(ID)
);









