--/*
--   요구사항
--   음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
--   음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
--   당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
--*/
--
---- 음료수
---- TBL_SOFT_DRINK
---- 이름, 가격, 재고, 재조일
--CREATE SEQUENCE SEQ_SOFT_DRINK;
--CREATE TABLE TBL_SOFT_DRINK(
--   ID NUMBER CONSTRAINT PK_SOFT_DRINK PRIMARY KEY,
--   SOFT_DRINK_NAME VARCHAR2(255) NOT NULL,
--   SOFT_DRINK_PRICE NUMBER DEFAULT 0,
--   SOFT_DRINK_STOCK NUMBER DEFAULT 999,
--   SOFT_DRINK_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--
---- 상품
---- TBL_PRODUCT
---- 이름, 재고
--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--   PRODUCT_NAME VARCHAR2(255) NOT NULL,
--   PRODUCT_STOCK NUMBER DEFAULT 999
--);
--
---- 사용자
---- TBL_USER
---- 이름, 주소, 번호
--CREATE SEQUENCE SEQ_USER;
--CREATE TABLE TBL_USER(
--   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,   
--   USER_NAME VARCHAR2(255) NOT NULL,
--   USER_ADDRESS VARCHAR2(255) NOT NULL,
--   USER_PHONE VARCHAR2(255) NOT NULL
--);
--
---- 주문
---- TBL_ORDER
---- 주문날짜, USER_ID, SOFT_DRINK_ID
--CREATE SEQUENCE SEQ_ORDER;
--CREATE TABLE TBL_ORDER(
--   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
--   ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   USER_ID NUMBER,
--   SOFT_DRINK_ID NUMBER,
--   CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
--   REFERENCES TBL_USER(ID),
--   CONSTRAINT FK_ORDER_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
--   REFERENCES TBL_SOFT_DRINK(ID)
--);
--
---- 당첨(운)
---- TBL_LOTTERY
---- SOFT_DRINK_ID
--CREATE SEQUENCE SEQ_LOTTERY;
--CREATE TABLE TBL_LOTTERY(
--   ID NUMBER CONSTRAINT PK_LOTTERY PRIMARY KEY,
--   SOFT_DRINK_ID NUMBER,
--   CONSTRAINT FK_LOTTERY_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
--   REFERENCES TBL_SOFT_DRINK(ID)
--);
--
---- 추첨
---- TBL_CIRULATION
---- LOTTERY_ID, PRODUCT_ID
--CREATE SEQUENCE SEQ_CIRULATION;
--CREATE TABLE TBL_CIRULATION(
--   ID NUMBER CONSTRAINT PK_CIRULATION PRIMARY KEY,
--   LOTTERY_ID NUMBER,
--   PRODUCT_ID NUMBER,
--   CONSTRAINT FK_CIRULATION_LOTTERY FOREIGN KEY(LOTTERY_ID)
--   REFERENCES TBL_LOTTERY(ID),
--   CONSTRAINT FK_CIRULATION_PRODUCT FOREIGN KEY(PRODUCT_ID)
--   REFERENCES TBL_PRODUCT(ID)
--);
--
--
---- 배송
---- TBL_DELIVERY
---- PRODUCT_ID, USER_ID
--CREATE SEQUENCE SEQ_DELIVERY;
--CREATE TABLE TBL_DELIVERY(
--   ID NUMBER CONSTRAINT PK_DELIVERY PRIMARY KEY,
--   PRODUCT_ID NUMBER,
--   USER_ID NUMBER,
--   CONSTRAINT FK_DELIVERY_PRODUCT FOREIGN KEY(PRODUCT_ID)
--   REFERENCES TBL_PRODUCT(ID),
--   CONSTRAINT FK_DELIVERY_USER FOREIGN KEY(USER_ID)
--   REFERENCES TBL_USER(ID)
--);


/*
   요구사항
   이커머스 창업 준비중입니다. 기업과 사용자 간 거래를 위해 기업의 정보와 사용자 정보가 필요합니다.
   기업의 정보는 기업 이름, 주소, 대표번호가 있고
   사용자 정보는 이름, 주소, 전화번호가 있습니다. 결제 시 사용자 정보와 기업의 정보, 결제한 카드의 정보 모두 필요하며,
   상품의 정보도 필요합니다. 상품의 정보는 이름, 가격, 재고입니다.
   사용자는 등록한 카드의 정보를 저장할 수 있으며, 카드의 정보는 카드번호, 카드사, 회원 정보가 필요합니다.
*/

-- 회사(TBL_COMPANY)
-- 이름, 주소, 대표번호
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
   ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
   COMPANY_NAME VARCHAR2(255) NOT NULL,
   COMPANY_ADDRESS VARCHAR2(255) NOT NULL,
   COMPANY_PHONE VARCHAR2(255)
);

-- 사용자(TBL_MEMBER)
-- 이름, 주소, 전화번호
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
   MEMBER_NAME VARCHAR2(255) NOT NULL,
   MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
   MEMBER_PHONE VARCHAR2(255) NOT NULL
);

-- 상품(TBL_PRODUCT)
-- 이름, 가격, 재고
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_PRICE NUMBER DEFAULT 0,
   PRODUCT_STOCK NUMBER DEFAULT 999
);

-- 주문(TBL_ORDER)
-- MEMBER_ID, PRODUCT_ID
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
   MEMBER_ID,
   PRODUCT_ID,
   CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID),
   CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID)
);

-- 카드(TBL_CARD)
-- 카드이름, 카드은행, 카드날짜, 카드번호, MEMBER_ID
CREATE SEQUENCE SEQ_CARD;
CREATE TABLE TBL_CARD(
   ID NUMBER CONSTRAINT PK_CARD PRIMARY KEY,
   CARD_NAME VARCHAR2(255) NOT NULL,
   CARD_BANK VARCHAR2(255) NOT NULL,
   CARD_DATE DATE DEFAULT CURRENT_TIMESTAMP,
   MEMBER_ID NUMBER,
   CONSTRAINT FK_CARD_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID)
);

-- 결제(TBL_PAY) 
-- ORDER_ID, CARD_ID, COMPANY_ID
CREATE SEQUENCE SEQ_PAY;
CREATE TABLE TBL_PAY(
   ID NUMBER CONSTRAINT PK_PAY PRIMARY KEY,
   ORDER_ID NUMBER,
   CARD_ID NUMBER,
   COMPANY_ID NUMBER,
   CONSTRAINT FK_PAY_ORDER FOREIGN KEY(ORDER_ID)
   REFERENCES TBL_ORDER(ID),
   CONSTRAINT FK_PAY_CARD FOREIGN KEY(CARD_ID)
   REFERENCES TBL_CARD(ID),
   CONSTRAINT FK_PAY_COMPANY FOREIGN KEY(COMPANY_ID)
   REFERENCES TBL_COMPANY(ID)
);

CONSTRAINT FK_PAY_ORDER FOREIGN KEY(ORDER_ID)
REFERENCES TBL_ORDER(ID);



















