/*
   요구사항
   음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
   음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
   당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
*/

-- 음료수
-- TBL_SOFT_DRINK
-- 이름, 가격, 재고, 재조일
CREATE SEQUENCE SEQ_SOFT_DRINK;
CREATE TABLE TBL_SOFT_DRINK(
   ID NUMBER CONSTRAINT PK_SOFT_DRINK PRIMARY KEY,
   SOFT_DRINK_NAME VARCHAR2(255) NOT NULL,
   SOFT_DRINK_PRICE NUMBER DEFAULT 0,
   SOFT_DRINK_STOCK NUMBER DEFAULT 999,
   SOFT_DRINK_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 상품
-- TBL_PRODUCT
-- 이름, 재고
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_STOCK NUMBER DEFAULT 999
);

-- 사용자
-- TBL_USER
-- 이름, 주소, 번호
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,   
   USER_NAME VARCHAR2(255) NOT NULL,
   USER_ADDRESS VARCHAR2(255) NOT NULL,
   USER_PHONE VARCHAR2(255) NOT NULL
);

-- 주문
-- TBL_ORDER
-- 주문날짜, USER_ID, SOFT_DRINK_ID
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
   ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   USER_ID NUMBER,
   SOFT_DRINK_ID NUMBER,
   CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID),
   CONSTRAINT FK_ORDER_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
   REFERENCES TBL_SOFT_DRINK(ID)
);

-- 당첨(운)
-- TBL_LOTTERY
-- SOFT_DRINK_ID
CREATE SEQUENCE SEQ_LOTTERY;
CREATE TABLE TBL_LOTTERY(
   ID NUMBER CONSTRAINT PK_LOTTERY PRIMARY KEY,
   SOFT_DRINK_ID NUMBER,
   CONSTRAINT FK_LOTTERY_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
   REFERENCES TBL_SOFT_DRINK(ID)
);

-- 추첨
-- TBL_CIRULATION
-- LOTTERY_ID, PRODUCT_ID
CREATE SEQUENCE SEQ_CIRULATION;
CREATE TABLE TBL_CIRULATION(
   ID NUMBER CONSTRAINT PK_CIRULATION PRIMARY KEY,
   LOTTERY_ID NUMBER,
   PRODUCT_ID NUMBER,
   CONSTRAINT FK_CIRULATION_LOTTERY FOREIGN KEY(LOTTERY_ID)
   REFERENCES TBL_LOTTERY(ID),
   CONSTRAINT FK_CIRULATION_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID)
);


-- 배송
-- TBL_DELIVERY
-- PRODUCT_ID, USER_ID
CREATE SEQUENCE SEQ_DELIVERY;
CREATE TABLE TBL_DELIVERY(
   ID NUMBER CONSTRAINT PK_DELIVERY PRIMARY KEY,
   PRODUCT_ID NUMBER,
   USER_ID NUMBER,
   CONSTRAINT FK_DELIVERY_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID),
   CONSTRAINT FK_DELIVERY_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);
