CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255), 
	MEMBER_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
	
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_COMMENT VARCHAR2(255),
	ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
	);
	

CREATE SEQUENCE SEQ_POST;
CREATE SEQUENCE SEQ_WRITER;
CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_WRITER(
	ID NUMBER CONSTRAINT PK_WRITER PRIMARY KEY,
	WRITER_NICKNAME  VARCHAR2(255) UNIQUE NOT NULL
);

CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_ARTICLE VARCHAR2(255) NOT NULL,
	WRITER_ID NUMBER,
	CONSTRAINT FK_POST_WRITER FOREIGN KEY(WRITER_ID)
	REFERENCES TBL_WRITER(ID)
);


CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR(255) NOT NULL,
	REPLY_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	WRITER_ID NUMBER,
	CONSTRAINT FK_REPLY_WRITER FOREIGN KEY(WRITER_ID)
	REFERENCES TBL_WRITER(ID)
);


