/*

   요구사항
   안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
   광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
   광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
   기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.

*/

-- 회사
CREATE SEQUENCE SEQ_COMPANY;
-- 이름, 주소, 대표번호, 기업종류
CREATE TABLE TBL_COMPANY(
   ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
   COMPANY_NAME VARCHAR2(255) NOT NULL UNIQUE,
   COMPANY_ADDRESS VARCHAR2(255) NOT NULL,
   COMPANY_PHONE VARCHAR2(255),
   COMPNAY_TYPE VARCHAR2(255) NOT NULL,
   CONSTRAINT COMPNAY_BAN_TYPE CHECK(COMPNAY_TYPE IN ('스타트업', '중소기업', '중견기업', '대기업'))
);

-- 광고
-- 제목, 내용
CREATE SEQUENCE SEQ_AD;
CREATE TABLE TBL_AD(
   ID NUMBER CONSTRAINT PK_AD PRIMARY KEY,
   AD_TITLE VARCHAR2(255) NOT NULL,
   AD_CONTENT VARCHAR2(255) NOT NULL
);

-- 신청
CREATE SEQUENCE SEQ_AD_APPLY;
CREATE TABLE TBL_AD_APPLY(
   ID NUMBER CONSTRAINT PK_AD_APPLY PRIMARY KEY,
   COMPANY_ID NUMBER,
   AD_ID NUMBER,
   CONSTRAINT FK_AD_APPLY_COMPANY FOREIGN KEY(COMPANY_ID)
   REFERENCES TBL_COMPANY(ID),
   CONSTRAINT FK_AD_APPLY_AD FOREIGN KEY(AD_ID)
   REFERENCES TBL_AD(ID)
);


-- 대카테고리(A)
CREATE SEQUENCE SEQ_CATEGORY_A;
CREATE TABLE TBL_CATEGORY_A(
   ID NUMBER CONSTRAINT PK_CATEGORY_A PRIMARY KEY,
   CATEGORY_A_NAME VARCHAR2(255) NOT NULL,
   AD_ID NUMBER,
   CONSTRAINT FK_CATEGORY_A_AD FOREIGN KEY(AD_ID)
   REFERENCES TBL_AD(ID)
);

-- 중카테고리(B)
CREATE SEQUENCE SEQ_CATEGORY_B;
CREATE TABLE TBL_CATEGORY_B(
   ID NUMBER CONSTRAINT PK_CATEGORY_B PRIMARY KEY,
   CATEGORY_B_NAME VARCHAR2(255) NOT NULL,
   CATEGORY_A_ID NUMBER,
   CONSTRAINT FK_CATEGORY_B_CATEGORY_A FOREIGN KEY(CATEGORY_A_ID)
   REFERENCES TBL_CATEGORY_A(ID)
);

-- 소카테고리(C)
CREATE SEQUENCE SEQ_CATEGORY_C;
CREATE TABLE TBL_CATEGORY_C(
   ID NUMBER CONSTRAINT PK_CATEGORY_C PRIMARY KEY,
   CATEGORY_C_NAME VARCHAR2(255) NOT NULL,
   CATEGORY_B_ID NUMBER,
   CONSTRAINT FK_CATEGORY_C_CATEGORY_B FOREIGN KEY(CATEGORY_B_ID)
   REFERENCES TBL_CATEGORY_B(ID)
);





















