-- 인터프리트 언어
-- 마지막에 ;
-- CTRL + ENTER : 한 줄 실행
--
--SELECT SYSDATE FROM DUAL;
--
-- DDL
-- 주석(CTRL + /)
-- 한 줄 복사 (CTRL + ALT + 화살표)
-- 줄 바꿈 (CTRL + SHIFT + 화살표)
-- 한 줄 삭제 (CTRL + D)
-- 한 줄 실행 (CTRL + ENTER)
--
-- DDL
--	CREATE TABLE 테이블명(
--	컬럼명 타입 제약조건1, 제약조건2,
--	컬럼명 타입 제약조건1, 제약조건2,
--	컬럼명 타입 제약조건1, 제약조건2,
--);
--
-- 예약어 사용 X
-- TBL_: 테이블
-- 스네이크 표기법
--CREATE TABLE TBL_TEST(
--	ID NUMBER CONSTRAINT PK_TEST PRIMARY KEY,
--	TEST_NAME VARCHAR2(255),
--	TEST_AGE NUMBER
--	
--);
--
-- DML
--
--SELECT * FROM TBL_TEST;
--
-- CREATE TABLE TBL_ANIMAL(
--    -- 동물
--    -- 이름(NAME), 나이(AGE), 종류(SPECIES), 생일(BIRTH_DAY)
--    ID NUMBER CONSTRAINT PK_ANIMAL PRIMARY KEY,
--    ANIMAL_NAME VARCHAR2(255),
--    ANIMAL_AGE NUMBER,
--    ANIMAL_SPECIES VARCHAR2(255),
--    ANIMAL_BIRTH_DAY DATE
--    
--);
--
--SELECT  * FROM TBL_ANIMAL;
--
-- 게시판
-- 글제목(TITLE), 내용(CONTENT), 작성시간(CREATE_AT)
-- 테이블 만들고 조회
-- DML의 CREATE TABLE
--
--CREATE TABLE TBL_POST(
--	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
--	POST_TITLE VARCHAR2(255),
--	POST_CONTENT VARCHAR2(255),
--	POST_CREATE_AT DATE,
--	POST_CREATE_TIME TIMESTAMP
--);
--
--SELECT *FROM TBL_POST;
--
-- 시퀀스 생성
--CREATE SEQUENCE SEQ_POST;
--
-- ALTER
-- 컬럼 추가(ADD)
--
-- 먹이 컬럼 추가(FEED)
-- ALTER TABLE TBL_ ADD 컬럼명 타입;
--ALTER TABLE TBL_ANIMAL ADD ANIMAL_FEED VARCHAR2(255);
--
-- 컬럼 변경(MODIFY)
--ALTER TABLE TBL_ANIMAL MODIFY ANIMAL_FEED NUMBER;
--ALTER TABLE TBL_ANIMAL MODIFY ANIMAL_FEED VARCHAR(255);
--
-- ANIMAL_BIRTH_DAY -> TIMESTAMP로 변경
--ALTER TABLE TBL_ANIMAL MODIFY ANIMAL_BIRTH_DAY TIMESTAMP;
--
-- 컬럼명 변경(RENAME COLUMN)
--ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_BIRTH_DAY TO ANIMAL_BIRTH; 
--
-- ANIMAL_NAME -> ANIMAL_OWNER 
--ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_NAME TO ANIMAL_OWNER;
--
-- 테이블명 변경 TBL_ANIMAL -> TBL_PERSON
--ALTER TABLE TBL_ANIMAL RENAME TO TBL_PERSON;
--ALTER TABLE TBL_PERSON RENAME TO TBL_ANIMAL;
--
--SELECT*FROM TBL_ANIMAL;
--SELECT*FROM TBL_PERSON;
--
-- DROP 
-- DROP TABLE 이름;
-- DROP SEQUENCE 이름;
--
--DROP TABLE TBL_TEST;
--
--// 테이블 데이터 초기화
--TRUNCATE TABLE TBL_PERSON;
--TRUNCATE TABLE TBL_ANIMAL;
--
-- 테이블 생성 + 제약 조건
-- TBL_USER(유저)
-- ID, 이메일(USER_EMAIL), 비밀번호(USER_PASSWORD), 이름(USER_NAME), 휴대폰 번호(USER_PHONE)
-- 회원가입일(USER_CREATE_AT), 
-- 업데이트 날짜(USER_UPDATE_AT)
--
--CREATE SEQUENCE SEQ_USER;
--CREATE TABLE TBL_USER(
--	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
--	USER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
--	USER_PASSWORD VARCHAR2(255) NOT NULL,
--	USER_NAME VARCHAR2(255),
--	USER_PHONE VARCHAR2(255) NOT NULL,
--	USER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);

-- 자동차 테이블(TBL_CAR)
-- 이름(NAME), 브랜드(BRAND), 가격(PRICE), 컬러(COLOR), 출고일자(CREATE_AT), 인승(SEATER)
-- 제약조건 알아서

CREATE SEQUENCE SEQ_CAR;

CREATE TABLE TBL_CAR(
	ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_NAME VARCHAR2(255) NOT NULL,
	CAR_BRAND VARCHAR2(255) NOT NULL,
	CAR_COLOR VARCHAR2(255) NOT NULL,
	CAR_CREATE_AT TIMESTAMP,
	CAR_SEATER NUMBER NOT NULL
);

SELECT*FROM TBL_CAR;

ALTER TABLE TBL_CAR ADD CAR_PRICE NUMBER DEFAULT 0;
ALTER TABLE TBL_CAR MODIFY CAR_SEATER NUMBER DEFAULT 4;

-- 1. CAR_NAME 
-- 컬럼 이름 변경 -> CAR_MODEL

ALTER TABLE TBL_CAR RENAME COLUMN CAR_NAME TO CAR_MODEL;

-- 2. CAR_PRICE
-- 컬럼 타입 변경 -> VARCHAR2(255)
ALTER TABLE TBL_CAR MODIFY CAR_PRICE VARCHAR2(255) NOT NULL;

-- 3. CAR_COLOR
-- 컬럼 삭제
ALTER TABLE TBL_CAR DROP COLUMN CAR_COLOR;


-- 제약 조건 수정
-- NOT NULL, UNIQUE

ALTER TABLE TBL_CAR MODIFY CAR_MODEL NOT NULL;

-- UNIQUE
-- ADD CONSTRAINT
-- CAR_MODEL에 UNIQUE 추가
-- 번거로우니 처음 넣을 때 제대로 넣자
ALTER TABLE TBL_CAR ADD CONSTRAINT UK_CAR UNIQUE (CAR_MODEL);
-- 유니크 삭제
ALTER TABLE TBL_CAR DROP CONSTRAINT UK_CAR;

-- EX)
-- ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(ID);

-- DEFAULT 추가, 수정, 삭제
-- CAR_COLOR
-- 오라클은 값이 ''(싱글쿼터, 홑따옴표)

ALTER TABLE TBL_CAR MODIFY CAR_BRAND DEFAULT '블랙';

-- 기존 값을 그대로 변경
ALTER TABLE TBL_CAR MODIFY CAR_BRAND DEFAULT '레드';

-- 삭제
ALTER TABLE TBL_CAR MODIFY CAR_BRAND DEFUALT NULL;

-- ex)
-- ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(ID);


-- 1. CAR_SEATER의 DEFAULT 값을 8로 변경
-- 2. CAR_BRAND UNIQUE 추가

ALTER TABLE TBL_CAR MODIFY CAR_SEATER DEFAULT 8; 
ALTER TABLE TBL_CAR ADD CONSTRAINT UK_BRAND UNIQUE (CAR_BRAND);

-- 관계
-- 유저(TBL_USER), 구매(TBL_ORDER)

CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255) NOT NULL,
	USER_ADDRESS VARCHAR2(255) NOT NULL,
	USER_PHONE VARCHAR2(255) DEFAULT '010-0000-0000'
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_PRODUCT_NAME VARCHAR2(255) NOT NULL,
	ORDER_STOCK NUMBER DEFAULT 1,
	USER_ID NUMBER,
	CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID)
)


-- 정규화
-- 상품 테이블(TBL_PRODUCT)
-- 상품 이름, 상품 가격, 상품 재고

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL UNIQUE,
	PRODUCT_PRICE NUMBER DEFAULT 0 NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 0
);
-- 네임에 유니크 처리할 것


-- 선물 테이블(TBL_GIFT)
-- 선물 주소, 선물 수량, 상품 아이디
CREATE SEQUENCE SEQ_GIFT;
CREATE TABLE TBL_GIFT(
	ID NUMBER CONSTRAINT PK_GIFT PRIMARY KEY,
	GIFT_ADDRESS VARCHAR2(255) NOT NULL,
	GIFT_AMOUNT VARCHAR2(255) NOT NULL,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_GIFT_PRODUCT_ID FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)	
);

-- 






